### ISSUE TITLE
NotesList - commandAction: elseif -> switch

### ISSUE THREAD

**Issue by sp0rk** [NotesTeam/TaskBook-J2ME#3]
http://softwareengineering.stackexchange.com/questions/154500/how-is-a-switch-statement-better-than-a-series-of-if-statements

> The power of switch is twofold:
> 
> It is more descriptive
> It saves CPU cycles
> Your post already comments on the descriptiveness of switch compared to a chain of ifs, so I will concentrate on part 2.
> 
> If the number of switch labels is N, a chain of ifs takes O(N) to dispatch, while a switch always dispatches in O(1). This is how it is done: compiler places addresses of switch labels into an array, computes an index based on the label values, and performs a jump directly, without comparing the switch expression to value one by one. In case of strings used as switch labels, the compiler produces a hash table, which looks up an address in O(1) as well.
> 
> When the number of switch becomes high (above 100), converting between switch and a chain of ifs could no longer be regarded as a micro-optimization: time savings may be very significant, especially in tight loops. If a profiler tells you that your chain of ifs is taking a significant time, rewriting as a switch may very well be a solution.

**Comment by wzieba** [comment]
Switch statement  cannot be used on objects of `Command`

**Comment by sp0rk** [comment]
Brainfart on my behalf. Sorry mate.
